# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
es:
  languageCode: es-419
#  contentDir: content/es
  menu:
    main:
    - name: Inicio
      #url: '#about'
      url: es
      weight: 10
    - name: Proyectos
      #url: '#projects'
      url: post
      weight: 20
    - name: Equipo
      #url: '#team'
      url: people
      weight: 30
    - name: Publicaciones
    #  url: '#publications'
      url: publication
      weight: 40
    - name: Posts
    #  url: '#posts'
      url: event
      weight: 50
    - name: Contacto
      #url: '#contact'
      url: contact
      weight: 60


# Uncomment the lines below to configure your website in a second language.

#en:
#  languageCode: en-us
#  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
#  contentDir: content/en
##  title: Chinese website title...
##  params:
##    description: Site description in Chinese...

